### ISSUE TITLE
Pb with Centos8

### ISSUE THREAD

**Issue by Isma399** [EsupPortail/esup-pam-cas#10]
Hello, 

I'm validating Centos8 to deploy cyrus-imap on a new cluster.
In this cluster, there are some IMAP proxy who authenticate webmail users with Proxy Ticket.

Configuration is deployed with Ansible.
It's OK and in production on Centos7.

Manually install on Centos8 is successful.
Pass the castest requires to downgrade crypto policies (about a DH key too small, however, webmail has a 2048 bit length certificate) : 
`update-crypto-policies --set LEGACY`

Then, I've tried to connect to the webmail. CAS log is OK:

> 2020-06-03 12:15:09,957 INFO [org.jasig.cas.authentication.AuthenticationManagerImpl] - org.jasig.cas.authentication.handler.support.HttpBasedServiceCredentialsAuthenticationHandler successfully authenticated [callbackUrl: https://webmail-preprod.MYDOMAIN/horde/casProxy.php]
2020-06-03 12:15:09,957 INFO [org.jasig.cas.authentication.AuthenticationManagerImpl] - Resolved principal https://webmail-preprod.MYDOMAIN/horde/casProxy.php

And IMAP Proxy gets proxy tickets :

> 2020-06-03 12:15:21,937 INFO [org.jasig.cas.CentralAuthenticationServiceImpl] - Granted proxy ticket [ST-38664-qTsAKc6ORc6WR3dCdf4S-cas.MYDOMAIN] for service [imap://preprod.MYDOMAIN] for user [USER]
2020-06-03 12:15:21,995 INFO [org.jasig.cas.CentralAuthenticationServiceImpl] - Granted proxy ticket [ST-38665-9DqeVNvahLwJLfsX1dwm-cas.MYDOMAIN] for service [imap://preprod.MYDOMAIN] for user [USER]
2020-06-03 12:15:22,062 INFO [org.jasig.cas.CentralAuthenticationServiceImpl] - Granted proxy ticket [ST-38666-q2hNR95FOP6kWpjK3UZp-cas.MYDOMAIN] for service [imap://preprod.MYDOMAIN] for user [USER]

But, imap proxy is not happy with this tickets, /var/log/messages (on imap-proxy/centos8) : 

> Jun  3 12:15:18 imap-proxy-3-preprod saslauthd[1145]:                : auth failure: [user=USER] [service=imap] [realm=] [mech=pam] [reason=PAM auth error]

On Centos7, log is ok:

> Jun  3 12:22:34 imap-proxy-1-preprod PAM_cas[2976]: USER 'USER' AUTHENTICATED WITH CACHED CAS PT:ST-39814-DOWGRJJqoegbPuGauNBh-cas.MYDOMAIN

```
# cat /etc/pam_cas.conf
host cas.MYDOMAIN
uriValidate /cas/proxyValidate
ssl on
debug on
trusted_ca /etc/ssl/certs/webmail.cachain
cacheDirectory /var/cache/pam_cas
```

I've tried with SELINUX enforcing or permissive, no changes and no log (except some context to give to saslauthd, fix).
cacheDirectory is accessed with castest.

For now, I'm quite stucked, maybe it's trivial to make it work but I don't where to look for.
Thanks
If you need more test on Centos8, I'll be happy to make it

**Comment by Isma399** [comment]
Logging every debug
>cat /etc/rsyslog.d/debugging.conf
>*.debug      /var/log/debug.log`

I've got this errors in /var/log/debug.log : 

> Jun  4 12:27:27 imap-proxy-3-preprod PAM_cas[2614]: ---- request :#012GET /cas/proxyValidate?ticket=ST-39646-5VHmPY9j3eXuyPhLhf3A-cas.<MYDOMAIN>&service=imap://preprod.<MYDOMAIN> HTTP/1.1#015#012Connection: close#015#012Host: cas.<MYDOMAIN>
Jun  4 12:27:27 imap-proxy-3-preprod PAM_cas[2614]: ---- response :#012HTTP/1.1 200 OK#015#012Date: Thu, 04 Jun 2020 10:27:27 GMT#015#012Content-Type: text/html;charset=UTF-8#015#012Content-Language: fr-FR#015#012Content-Length: 299#015#012Connection: close#015#012#015#012#012#012#012#012<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>#012#011<cas:authenticationSuccess>#012#011#011<cas:user><USER></cas:user>#012#012#012#011#011<cas:proxies>#012#012#011#011#011<cas:proxy>https://webmail-preprod.<MYDOMAIN>/horde/casProxy.php</cas:proxy>#012#012#011#011</cas:proxies>#012#012#011</cas:authenticationSuccess>#012</cas:serviceResponse>
Jun  4 12:27:27 imap-proxy-3-preprod PAM_cas[2614]: USER '<USER>' AUTHENTICATED WITH CAS PT:ST-39646-5VHmPY9j3eXuyPhLhf3A-cas.<MYDOMAIN>
Jun  4 12:27:28 imap-proxy-3-preprod PAM_cas[2613]: ---- request :#012GET /cas/proxyValidate?ticket=ST-39646-5VHmPY9j3eXuyPhLhf3A-cas.<MYDOMAIN>&service=imap://preprod.<MYDOMAIN> HTTP/1.1#015#012Connection: close#015#012Host: cas.<MYDOMAIN>
Jun  4 12:27:28 imap-proxy-3-preprod PAM_cas[2613]: ---- response :#012HTTP/1.1 200 OK#015#012Date: Thu, 04 Jun 2020 10:27:28 GMT#015#012Content-Type: text/plain;charset=UTF-8#015#012Content-Language: fr-FR#015#012Content-Length: 252#015#012Connection: close#015#012#015#012#012#012#012<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>#012#011<cas:authenticationFailure code='INVALID_TICKET'>#012#011#011le ticket &#039;ST-39646-5VHmPY9j3eXuyPhLhf3A-cas.<MYDOMAIN>&#039; est inconnu#012#011</cas:authenticationFailure>#012</cas:serviceResponse>
Jun  4 12:27:28 imap-proxy-3-preprod PAM_cas[2613]: authentication failure for user '<USER>' : bad CAS ticket. PT=ST-39646-5VHmPY9j3eXuyPhLhf3A-cas.<MYDOMAIN>
Jun  4 12:27:33 imap-proxy-3-preprod PAM_cas[2615]: ---- request :#012GET /cas/proxyValidate?ticket=ST-39665-yJs0vvTer32GOgf62Z4e-cas.univ-brest.fr&service=imap://preprod.<MYDOMAIN> HTTP/1.1#015#012Connection: close#015#012Host: cas.<MYDOMAIN>
Jun  4 12:27:33 imap-proxy-3-preprod PAM_cas[2615]: ---- response :#012HTTP/1.1 200 OK#015#012Date: Thu, 04 Jun 2020 10:27:33 GMT#015#012Content-Type: text/html;charset=UTF-8#015#012Content-Language: fr-FR#015#012Content-Length: 299#015#012Connection: close#015#012#015#012#012#012#012#012<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>#012#011<cas:authenticationSuccess>#012#011#011<cas:user><USER></cas:user>#012#012#012#011#011<cas:proxies>#012#012#011#011#011<cas:proxy>https://webmail-preprod.<MYDOMAIN>/horde/casProxy.php</cas:proxy>#012#012#011#011</cas:proxies>#012#012#011</cas:authenticationSuccess>#012</cas:serviceResponse>
Jun  4 12:27:33 imap-proxy-3-preprod PAM_cas[2615]: USER '<USER>' AUTHENTICATED WITH CAS PT:ST-39665-yJs0vvTer32GOgf62Z4e-cas.<MYDOMAIN>
Jun  4 12:27:35 imap-proxy-3-preprod PAM_cas[2616]: ---- request :#012GET /cas/proxyValidate?ticket=ST-39665-yJs0vvTer32GOgf62Z4e-cas.<MYDOMAIN>&service=imap://preprod.<MYDOMAIN> HTTP/1.1#015#012Connection: close#015#012Host: cas.<MYDOMAIN>
Jun  4 12:27:35 imap-proxy-3-preprod PAM_cas[2616]: ---- response :#012HTTP/1.1 200 OK#015#012Date: Thu, 04 Jun 2020 10:27:35 GMT#015#012Content-Type: text/plain;charset=UTF-8#015#012Content-Language: fr-FR#015#012Content-Length: 252#015#012Connection: close#015#012#015#012#012#012#012<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>#012#011<cas:authenticationFailure code='INVALID_TICKET'>#012#011#011le ticket &#039;ST-39665-yJs0vvTer32GOgf62Z4e-cas.<MYDOMAIN>&#039; est inconnu#012#011</cas:authenticationFailure>#012</cas:serviceResponse>
Jun  4 12:27:35 imap-proxy-3-preprod PAM_cas[2616]: authentication failure for user '<USER>' : bad CAS ticket. PT=ST-39665-yJs0vvTer32GOgf62Z4e-cas.<MYDOMAIN>

**Comment by prigaux** [comment]
tmp is not the best place, esp nowadays with systemd PrivateTmp. I suggest you put it somewhere else.

Another thing you can try is `ldd /tmp/esup-pam-cas-master/sources/pam_cas.so`

**Comment by Isma399** [comment]
Excuse-me, I 've tried /tmp do give a test.
But I go back to /lib64/security
Thanks for your answer, I edited my post accordingly

**Comment by Isma399** [comment]
On Centos8

>ldd /usr/lib64/security/pam_cas.so

        linux-vdso.so.1 (0x00007fff141f3000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f365db60000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f365d681000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f365d472000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f365d0af000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f365ce98000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f365cc94000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f365ca74000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f365c84a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f365dffa000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f365c644000)

**Comment by Isma399** [comment]
On centos7 :

> ldd /usr/lib64/security/pam_cas.so

        linux-vdso.so.1 =>  (0x00007ffc423bd000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007fb7e2809000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fb7e23a6000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007fb7e2197000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb7e1dc9000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fb7e1b7c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fb7e1893000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fb7e168f000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fb7e145c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb7e1258000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb7e1042000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007fb7e0e19000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb7e2c81000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fb7e0c09000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fb7e0a05000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb7e07ec000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb7e05d0000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007fb7e03ca000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fb7e01a3000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fb7dff41000)

**Comment by Isma399** [comment]
Is there any missings librairies on Centos8?

**Comment by Isma399** [comment]
OK, i found my mistake.
I've compiled pam_cas.so in /tmp directory and then copy it to /lib64/security.
That don't work.

I changed the make file to have a good path and everything goes well.
Thank for your interest.
