### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by brenard** [EsupPortail/esup-pam-cas#2]
Pour faciliter le déploiement sur nos serveurs, j'ai ajouté de quoi construire un paquet Debian facilement. J'ai récemment mi tous cela dans un branche _debian_ de mon _fork_ de ce repos : https://github.com/Easter-eggs/esup-pam-cas/tree/debian

Serait-il envisageable de créer une branche _debian_ sur ce repos pour que je vous propose une _Pull-Request_ sur le sujet ?

**Comment by prigaux** [comment]
Vu que c'est dans un répertoire bien clair, je propose de mettre ça directement dans "master". Je veux bien une pull-request  pour ça :)

**Comment by brenard** [comment]
Ok, j'adapte mon code et je propose une pull-request pour ça.

**Comment by brenard** [comment]
C'est fait : #3
