### ISSUE TITLE
Error validating server certificate

### ISSUE THREAD

**Issue by John222** [EsupPortail/esup-pam-cas#5]
Hi guys. When we try to use your pam cas module and execute

`./castest`

we always get a "error validating server certificate". As next the output:

```bash
We use SSL as configured
We connect to host <host system removed>
Certificate verification error: 2
---------------------------------------------------------------

invalid ticket : error validating server certificate
```

We checked the issuer certificate the connection (ssl3,tls, ciphers), all seems to be fine when we are executing a

```openssl s_client -connect <host system removed>:443```

Do you have any hints what could be the issue?

- Our client system is a "Debian jessie (latest patch level)
- We compiled the "Makefile.redhat"
- Our cas server is served through a nginx webserver

**Comment by prigaux** [comment]
Hi,

castest works nicely for our cas servers. esup-pam-cas simply uses openssl.

Is your host public? or maybe you can find another host (non cas) that reproduces?

**Comment by John222** [comment]
Hi Prigaux

we tried now a ssl website like www.facebook.com. The connection worked! So the question is now. What they do different in conjunction to webserver ssl settings.

**Comment by prigaux** [comment]
Closing old ticket
